# Misc Code For Visualization

In [ ]:
import base64
from IPython.display import Image, display

def mm_ink(graph: str):
    graphbytes = graph.encode("utf-8")
    base64_string = base64.urlsafe_b64encode(graphbytes).decode("ascii")
    return "https://mermaid.ink/img/" + base64_string

def mm(graph: str):
    display(Image(url=mm_ink(graph)))

# Build a Rambam Q&A Chatbot with LlamaIndex + OpenAI + Gradio

In this notebook, we build a source-grounded Q&A chatbot over Rambam’s *Mishneh Torah*.


# Big Picture: What Is RAG?


# Tools we will use


- **LlamaIndex** for indexing and retrieval
    https://developers.llamaindex.ai/python/framework/
  - **OpenAI API** for embeddings and answer generation  
- **Gradio** for the chat interface  

---

In [ ]:
# @title
from IPython.display import Markdown,display
display(Markdown("# RAG Flow for Rambam Q&A"))

mm("""
flowchart TD
    A["User Question<br/>What does Rambam say about repentance?"]
    A --> B["Embed Query<br/>q = [0.82, -0.14, 0.33, 0.71]"]
    B --> C["Vector Search<br/>Find K Most Similar Chunks"]

    D1["Rambam Chunk 1<br/>Hilchot Teshuva 2:1"]
    D2["Rambam Chunk 2<br/>Hilchot Deot 1:3"]
    D3["Rambam Chunk 3<br/>Hilchot Teshuva 7:4"]

    D1 --> C
    D2 --> C
    D3 --> C

    C --> E["Return Top K Matches"]
    E --> F["Prompt to LLM<br/>Question + Sources"]
    F --> G["Final Answer<br/>with citations"]
""")

# RAG Flow for Rambam Q&A

# Load DataFrame

In [5]:
import pandas as pd

In [48]:
df = pd.read_parquet('rambam_df.parquet')

In [52]:
df.groupby(['section','chapter']).head(1)

,ref,section,section_type,chapter,number,text
0,"Mishneh Torah, Transmission of the Oral Law 1",Transmission of the Oral Law,intro,0,1,"<b>The Rambam's Introduction</b><sup class=""fo..."
45,"Mishneh Torah, Positive Mitzvot 1",Positive Mitzvot,positive_mitzvah,0,0,The first of the positive commandments is the ...
293,"Mishneh Torah, Negative Mitzvot 1",Negative Mitzvot,negative_mitzvah,0,0,The first mitzvah of the negative commandments...
663,"Mishneh Torah, Overview of Mishneh Torah Conte...",Overview of Mishneh Torah Contents,overview,0,1,I have seen fit to divide this work into fourt...
677,"Mishneh Torah, Foundations of the Torah 1:1",Foundations of the Torah,halacha,1,1,The foundation of all foundations and the pill...
...,...,...,...,...,...,...
15690,"Mishneh Torah, Kings and Wars 8:1",Kings and Wars,halacha,8,1,When the army's troops enter the territory of ...
15701,"Mishneh Torah, Kings and Wars 9:1",Kings and Wars,halacha,9,1,Six precepts were commanded to Adam:<br>a) the...
15715,"Mishneh Torah, Kings and Wars 10:1",Kings and Wars,halacha,10,1,A Noachide who inadvertently violates one of h...
15727,"Mishneh Torah, Kings and Wars 11:1",Kings and Wars,halacha,11,1,"In the future, the Messianic king will arise a..."
15736,"Mishneh Torah, Kings and Wars 12:1",Kings and Wars,halacha,12,1,Do not presume that in the Messianic age any f...

In [56]:
from IPython.display import display, HTML
display(HTML(df.text[0]))

# Installs Needed
* Maybe need more if not using Colab

In [7]:
!pip install llama_index openai gradio

Collecting llama_index
  Downloading llama_index-0.14.21-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.32.0)
Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Collecting llama-index-core<0.15.0,>=0.14.21 (from llama_index)
  Downloading llama_index_core-0.14.21-py3-none-any.whl.metadata (2.6 kB)
Collecting llama-index-embeddings-openai<0.7,>=0.6.0 (from llama_index)
  Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl.metadata (401 bytes)
Collecting llama-index-llms-openai<0.8,>=0.7.0 (from llama_index)
  Downloading llama_index_llms_openai-0.7.7-py3-none-any.whl.metadata (3.0 kB)
Collecting nltk>=3.9.3 (from llama_index)
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.136.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.11.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.8)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.1)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.26)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.11)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.2)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.46.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.3)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (3.13.5)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading banks-2.4.2-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2,>=1.2.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting llama-index-workflows<3,>=2.14.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading llama_index_workflows-2.20.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (3.6.1)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (4.9.6)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (2.32.4)
Collecting setuptools>=80.9.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.21->llama_index) (2.0.49)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (0.12.0)
Collecting tinytag>=2.2.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading tinytag-2.2.1-py3-none-any.whl.metadata (20 kB)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.21->llama_index) (2.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.21->llama_index) (1.23.0)
Collecting griffe (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading griffe-2.0.2-py3-none-any.whl.metadata (12 kB)
Collecting llama-index-instrumentation>=0.4.3 (from llama-index-workflows<3,>=2.14.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.21->llama_index) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.21->llama_index) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.21->llama_index) (3.4.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)
Collecting griffecli==2.0.2 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading griffecli-2.0.2-py3-none-any.whl.metadata (1.2 kB)
Collecting griffelib==2.0.2 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading griffelib-2.0.2-py3-none-any.whl.metadata (1.3 kB)
Collecting colorama>=0.4 (from griffecli==2.0.2->griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.21->llama_index)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Downloading llama_index-0.14.21-py3-none-any.whl (7.1 kB)
Downloading llama_index_core-0.14.21-py3-none-any.whl (11.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 75.9 MB/s eta 0:00:00
Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl (7.7 kB)
Downloading llama_index_llms_openai-0.7.7-py3-none-any.whl (28 kB)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 52.2 MB/s eta 0:00:00
Downloading banks-2.4.2-py3-none-any.whl (35 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading llama_index_workflows-2.20.0-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.2/121.2 kB 7.1 MB/s eta 0:00:00
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 42.7 MB/s eta 0:00:00
Downloading tinytag-2.2.1-py3-none-any.whl (32 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl (16 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.6 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading griffe-2.0.2-py3-none-any.whl (5.1 kB)
Downloading griffecli-2.0.2-py3-none-any.whl (9.5 kB)
Downloading griffelib-2.0.2-py3-none-any.whl (142 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.4/142.4 kB 7.3 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: filetype, dirtyjson, tinytag, setuptools, nltk, mypy-extensions, marshmallow, griffelib, deprecated, colorama, typing-inspect, griffecli, llama-index-instrumentation, griffe, dataclasses-json, llama-index-workflows, banks, llama-index-core, llama-index-llms-openai, llama-index-embeddings-openai, llama_index
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: nltk
    Found existing installation: nltk 3.9.1
    Uninstalling nltk-3.9.1:
      Successfully uninstalled nltk-3.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Successfully installed banks-2.4.2 colorama-0.4.6 dataclasses-json-0.6.7 deprecated-1.3.1 dirtyjson-1.0.8 filetype-1.2.0 griffe-2.0.2 griffecli-2.0.2 griffelib-2.0.2 llama-index-core-0.14.21 llama-index-embeddings-openai-0.6.0 llama-index-instrumentation-0.5.0 llama-index-llms-openai-0.7.7 llama-index-workflows-2.20.0 llama_index-0.14.21 marshmallow-3.26.2 mypy-extensions-1.1.0 nltk-3.9.4 setuptools-82.0.1 tinytag-2.2.1 typing-inspect-0.9.0

#  What is LlamaIndex

* https://developers.llamaindex.ai/python/framework/

# Load OpenAI API Keys + Set as os environment variable

In [1]:
from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

## Configure OpenAI + LlamaIndex

We use OpenAI in two places:

1. **Embeddings** — turning Rambam text and user questions into vectors  
2. **LLM responses** — generating the final answer from retrieved sources

The defaults are pretty good, but I find that we are much better off using the larger embedding model!!!

In [2]:
from llama_index.llms.openai import OpenAI as LlamaOpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core import Settings



Settings.llm = LlamaOpenAI(model="gpt-4o-mini", temperature=0)
Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-large")

## Convert DataFrame Rows into LlamaIndex Documents

Each row in the dataframe becomes a `Document`.

The `text` field becomes the content.

The other fields become metadata, which lets us cite sources later.

**CODE MYSELF**

In [29]:
from llama_index.core import Document
def df_to_documents(df):
    documents = []

    for row in df.itertuples(index=False):
        metadata = {
            "ref": row.ref,
            "section": row.section,
            "section_type": row.section_type,
            "chapter": row.chapter,
            "number": row.number,

        }
        documents.append(
            Document(
                text=row.text,
                metadata=metadata
            )
        )

    return documents

documents = df_to_documents(df)

len(documents), documents[0]

(15741,
 Document(id_='caa8f732-770b-472f-bc15-06ee1cee5390', embedding=None, metadata={'ref': 'Mishneh Torah, Transmission of the Oral Law 1', 'section': 'Transmission of the Oral Law', 'section_type': 'intro', 'chapter': 0, 'number': 1}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, metadata_template='{key}: {value}', metadata_separator='\n', text_resource=MediaResource(embeddings=None, data=None, text='<b>The Rambam\'s Introduction</b><sup class="footnote-marker">1</sup><i class="footnote">The heading "Introduction" is not found in any of the manuscript editions of the <i>Mishneh Torah</i> and appears to be a printer\'s addition. Note <i>Hilchot Shechitah</i> 1:4, where the Rambam refers to "...the Oral Law, which is called `the mitzvah,\' as we explained in the beginning of this text."<br>By referring to these passages as "the beginning" of the text and not "the introduction to the text," the Rambam implies that the subject matter contained in these passages is an essential part of the <i>Mishneh Torah</i> and not merely an author\'s preamble.</i> <b>to the Mishneh Torah</b><br>"In the name of God, Lord of the world"<sup class="footnote-marker">2</sup><i class="footnote">Though this verse is omitted by many printed editions of the <i>Mishneh Torah,</i> it is included in the manuscript editions. It is also found at the beginning of the Rambam\'s other works, the Commentary on the Mishnah, <i>Sefer HaMitzvot,</i> and the Guide to the Perplexed. The Rambam\'s intention is to clarify that he does not see this work as an expression of his individual efforts alone, but that it was composed "In the name of God, the Lord of the world."</i> (Genesis 21:33)<br>"Then I will not be ashamed when I gaze at all Your mitzvot"<sup class="footnote-marker">3</sup><i class="footnote">The Rambam introduces every one of the books of the <i>Mishneh Torah</i> by quoting an appropriate verse from the Bible. It is possible to explain that he chose this verse for the introduction to the entire text in reply to objections he knew would arise to the <i>Mishneh Torah.</i> The Rambam\'s conception of his work as "a compilation of the entire Oral Law" would not be acceptable to many. Therefore, he begins by emphasizing that his actions were not presumptuous. There is no need for him to be "ashamed" at taking such a step. Since he can "gaze at all Your mitzvot" - i.e., has the knowledge of the entire Oral Law - he is obligated to try to communicate that knowledge to others, as stated in <i>Hilchot Talmud Torah 5:4 (Yayin Malchut).</i></i> (Psalms 119:6).<br>The mitzvot given to Moses at Mount Sinai were all given together with their explanations,<sup class="footnote-marker">4</sup><i class="footnote">By emphasizing that, at the revelation at Sinai, the mitzvot were given "together with their explanations," the Rambam stresses that the Written and Oral Laws cannot be viewed as two separate entities, but rather as two dimensions of a single whole. See also the Rambam\'s Introduction to his Commentary on the Mishnah, where he elaborates on the same concept.</i> as implied by [Exodus 24:12]: "And I will give you the tablets of stone, the Torah, and the mitzvah."<br>"The Torah" refers to the Written Law; "the mitzvah," to its explanation. [God] commanded us to fulfill "the Torah" according to [the instructions of] "the mitzvah."<sup class="footnote-marker">5</sup><i class="footnote">See <i>Emunah V\'De\'ot</i> (Discourse 3, Chapter 3), where Rav Sa\'adiah Gaon explains at length how the oral tradition is necessary to understand how to fulfill the mitzvot</i> "The mitzvah" is called the Oral Law.', path=None, url=None, mimetype=None), image_resource=None, audio_resource=None, video_resource=None, text_template='{metadata_str}\n\n{content}'))

## Build the Vector Index

In [32]:
from llama_index.core import VectorStoreIndex
index = VectorStoreIndex.from_documents(documents,show_progress=True)

Applying transformations:   0%|          | 0/1 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2048 [00:00<?, ?it/s]

Generating embeddings:   0%|          | 0/2026 [00:00<?, ?it/s]

# Optional, but recommended to Save Embeddings/Indexing for Later Querying. Should Save to VectorStore Like ChromaDB. Llama Index has tools for all this

## Save and Load the Index

Persisting the index prevents us from rebuilding embeddings every time.


```
from llama_index.core import VectorStoreIndex

index = VectorStoreIndex.from_documents(
    documents,
    show_progress=True
)

index.storage_context.persist(persist_dir="./storage")
```
Load later
```
from llama_index.core import StorageContext, load_index_from_storage

storage_context = StorageContext.from_defaults(
    persist_dir="./storage"
)

index = load_index_from_storage(storage_context)
```

### Let's see a sample embedding

In [42]:
vs = index.storage_context.vector_store.data.embedding_dict
len(next(iter(vs.values())))

3072

## 🔹 Query Engine: “Ask → Answer” All in One

In [44]:
query_engine = index.as_query_engine()
response = query_engine.query("What does Rambam say about free will?")

In [46]:
response.response

"Rambam asserts that free will is granted to all individuals, allowing them the choice to pursue either a righteous or wicked path. He emphasizes that each person has the capacity to know good and evil and to act according to their desires without external compulsion. This ability to choose is fundamental to human nature and is essential for moral responsibility. Rambam argues that if individuals were predetermined to be righteous or wicked, it would undermine the purpose of the Torah and the justice of divine retribution. Ultimately, he maintains that while everything occurs according to God's will, humans are still accountable for their actions, as they possess the freedom to make choices."

In [58]:
len(response.source_nodes)

2

**Retriever (Finding most relevant nodes) + Prompt + LLM → Final Answer**

---

### ⚙️ Customizing the Query Engine

In [59]:
query_engine = index.as_query_engine(similarity_top_k=5)
response = query_engine.query("What does Rambam say about free will?")

In [60]:
len(response.source_nodes)

5



You control:

* `text_qa_template` → how the answer is written (grounded, cited, etc.)
* `response_mode` → short vs structured answers
* `similarity_top_k` → how many sources are passed in
* `node_postprocessors` → reranking / refinement

👉 This controls **how the answer is generated**

---

## 🔍 Retriever — “Find the Right Sources” only

In [61]:
retriever = index.as_retriever(similarity_top_k=5)
nodes = retriever.retrieve("What does Rambam say about free will?")

In [62]:
nodes

[NodeWithScore(node=TextNode(id_='39768992-916f-4994-92e6-d750a945976d', embedding=None, metadata={'ref': 'Mishneh Torah, Repentance 5:1', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 1}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='a72bf164-316e-4630-bbc1-11e11bd61b37', node_type='4', metadata={'ref': 'Mishneh Torah, Repentance 5:1', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 1}, hash='82acaae479a438b419f0a26e7d80b12c3aaf07bb63a06f384b0e3eff2afd19f3')}, metadata_template='{key}: {value}', metadata_separator='\n', text='Free will is granted to all men. If one desires to turn himself to the path of good and be righteous, the choice is his. Should he desire to turn to the path of evil and be wicked, the choice is his.<br>This is [the intent of] the Torah\'s statement (Genesis 3:22 : "Behold, man has become unique as ourselves, knowing good and evil," i.e., the human species became singular in the world with no other species resembling it in the following quality: that man can, on his own initiative, with his knowledge and thought, know good and evil, and do what he desires. There is no one who can prevent him from doing good or bad. Accordingly, [there was a need to drive him from the Garden of Eden,] "lest he stretch out his hand [and take from the tree of life]."', mimetype='text/plain', start_char_idx=0, end_char_idx=756, text_template='{metadata_str}\n\n{content}'), score=0.6630534127386294),
 NodeWithScore(node=TextNode(id_='29369910-bab9-4462-832a-72acdba2e369', embedding=None, metadata={'ref': 'Mishneh Torah, Repentance 5:4', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 4}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='f6cde283-7f65-4c28-83ce-2dcab3213fed', node_type='4', metadata={'ref': 'Mishneh Torah, Repentance 5:4', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 4}, hash='eb832bc3fa39f9d513a86d538f522e45d877d15107f2de3f1a0b2188ab708b59')}, metadata_template='{key}: {value}', metadata_separator='\n', text='Were God to decree that an individual would be righteous or wicked or that there would be a quality which draws a person by his essential nature to any particular path [of behavior], way of thinking, attributes, or deeds, as imagined by many of the fools [who believe] in astrology - how could He command us through [the words of] the prophets: "Do this," "Do not do this," "Improve your behavior," or "Do not follow after your wickedness?"<br>[According to their mistaken conception,] from the beginning of man\'s creation, it would be decreed upon him, or his nature would draw him, to a particular quality and he could not depart from it.<br>What place would there be for the entire Torah? According to which judgement or sense of justice would retribution be administered to the wicked or reward to the righteous? Shall the whole world\'s Judge not act justly!<br>A person should not wonder: How is it possible for one to do whatever he wants and be responsible for his own deeds? - Is it possible for anything to happen in this world without the permission and desire of its Creator as [Psalms 135:6] states: "Whatever God wishes, He has done in the heavens and in the earth?"<br>One must know that everything is done in accord with His will and, nevertheless, we are responsible for our deeds.<br>How is this [apparent contradiction] resolved? Just as the Creator desired that [the elements of] fire and wind rise upward and [those of] water and earth descend downward, that the heavenly spheres revolve in a circular orbit, and all the other creations of the world follow the nature which He desired for them, so too, He desired that man have free choice and be responsible for his deeds, without being pulled or forced. Rather, he, on his own initiative, with the knowledge which God has granted him, will do anything that man is able to do.<br>Therefore, he is judged according to his deeds. If he does good, he is treated with beneficence. If he does bad, he is treated harshly. This is implied by the prophets\' statements: "This has been the doing of your hands” [Malachi 1:9]; "They also have chosen their own paths” [Isaiah 66:3].<br>This concept was also implied by Solomon in his statement [Ecclesiastes 11:9]: "Young man, rejoice in your youth... but, know that for all these things God will bring you to judgment," i.e., know that you have the potential to do, but in the future, you will have to account for your deeds.', mimetype='text/plain', start_char_idx=0, end_char_idx=2435, text_template='{metadata_str}\n\n{content}'), score=0.6193215132610812),
 NodeWithScore(node=TextNode(id_='5ca34145-c9ae-4c50-b56d-a39a2a5181c2', embedding=None, metadata={'ref': 'Mishneh Torah, Repentance 5:3', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 3}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='97fc62c0-e76e-4fd1-a57b-1ade006cf0f5', node_type='4', metadata={'ref': 'Mishneh Torah, Repentance 5:3', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 3}, hash='24942348835159cf71766144ab341407ec3c41558477f69d54f2da12989b3bd7')}, metadata_template='{key}: {value}', metadata_separator='\n', text='This principle is a fundamental concept and a pillar [on which rests the totality] of the Torah and mitzvot as [Deuteronomy 30:15] states: "Behold, I have set before you today life [and good, death and evil]." Similarly, [Deuteronomy 11:26] states, "Behold, I have set before you today [the blessing and the curse]," implying that the choice is in your hands.<br>Any one of the deeds of men which a person desires to do, he may, whether good or evil. Therefore, [Deuteronomy 5:26] states:<br>"If only their hearts would always remain this way." From this, we can infer that the Creator does not compel or decree that people should do either good or bad. Rather, everything is left to their [own choice].', mimetype='text/plain', start_char_idx=0, end_char_idx=703, text_template='{metadata_str}\n\n{content}'), score=0.6112433451479533),
 NodeWithScore(node=TextNode(id_='e2b54b3f-8e2c-4625-9ecb-6a8f32267d6f', embedding=None, metadata={'ref': 'Mishneh Torah, Human Dispositions 1:2', 'section': 'Human Dispositions', 'section_type': 'halacha', 'chapter': 1, 'number': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='dcb433a3-fb6e-492c-a15c-cbc31fa20521', node_type='4', metadata={'ref': 'Mishneh Torah, Human Dispositions 1:2', 'section': 'Human Dispositions', 'section_type': 'halacha', 'chapter': 1, 'number': 2}, hash='3e630ce285d1c9de944e7df3ee11cd0e9a4bc155df2a7fc776eeba8aad2ff970'), <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(node_id='8ff1b992-add6-41a2-9600-4cd69fdd342a', node_type='1', metadata={'ref': 'Mishneh Torah, Human Dispositions 1:2', 'section': 'Human Dispositions', 'section_type': 'halacha', 'chapter': 1, 'number': 2}, hash='e202aafdf3200ce57dd88c621833cfc053ad0894d1903fc22dd22cfc48cc2755')}, metadata_template='{key}: {value}', metadata_separator='\n', text='Nevertheless, these are merely tendencies, and they will not manifest themselves unless consciously developed. Also, these tendencies are, at all times, subject to man\'s control. We are granted free will, and choose our course of behavior.</i> Some traits he does not have from birth. He may have learned them from others,<sup class="footnote-marker">5</sup><i class="footnote">In <i>Shemonah Perakim</i>, Chapter 4, the Rambam writes: "From his youth, one becomes accustomed to acting in accordance with the accepted behavior of one\'s family and locale." In these few words, the Rambam includes all the people who might influence a person\'s character development: his parents, siblings, teachers, peers, and others. Also, note Chapter 6, Halachah 1.</i> or turned to them on his own.<sup class="footnote-marker">6</sup><i class="footnote">There are two ways of acquiring such traits</i> This may have come as a result of his own thoughts,<sup class="footnote-marker">7</sup><i class="footnote">i.e., an intuitive realization of the correctness of a certain course of behavior stemming from one\'s own creative thought.</i> or because he heard that this was a proper trait for him, which he ought to attain.<sup class="footnote-marker">8</sup><i class="footnote">i.e., through study a person understands the value of a certain character trait and sets out to acquire it.</i> [Therefore,] he accustomed himself to it until it became a part of himself.<sup class="footnote-marker">9</sup><i class="footnote">Unlike the inborn or easily acquired traits, these qualities must first be accepted intellectually. Then, through habitual actions, they become part of the personality. (See Halachah 7 for a detailed explanation of such a process of behavioral modification.)</i>', mimetype='text/plain', start_char_idx=3217, end_char_idx=4984, text_template='{metadata_str}\n\n{content}'), score=0.6090829936011503),
 NodeWithScore(node=TextNode(id_='6eeacb0e-e13b-4386-b0a3-4dea4ba2fda9', embedding=None, metadata={'ref': 'Mishneh Torah, Repentance 5:2', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 2}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='ec079b80-44b8-4797-881d-a9bb9de0476c', node_type='4', metadata={'ref': 'Mishneh Torah, Repentance 5:2', 'section': 'Repentance', 'section_type': 'halacha', 'chapter': 5, 'number': 2}, hash='fab1c28c32b7398dd9e37b6d9a3f4828a43f0b61b25880afbdf058386497aa86')}, metadata_template='{key}: {value}', metadata_separator='\n', text='A person should not entertain the thesis held by the fools among the gentiles and the majority of the undeveloped among Israel that, at the time of a man\'s creation, The Holy One, blessed be He, decrees whether he will be righteous or wicked.<br>This is untrue. Each person is fit to be righteous like Moses, our teacher, or wicked, like Jeroboam. [Similarly,] he may be wise or foolish, merciful or cruel, miserly or generous, or [acquire] any other character traits. There is no one who compels him, sentences him, or leads him towards either of these two paths. Rather, he, on his own initiative and decision, tends to the path he chooses.<br>This was [implied by the prophet,] Jeremiah who stated [Eichah 3:38: "From the mouth of the Most High, neither evil or good come forth." The Creator does not decree that a person should be good and refrain from being evil. Accordingly, it is the sinner, himself, who causes his own loss.<br>Therefore, it is proper for a person to cry and mourn for his sins and for what he has done to his soul, the evil consequences, he brought upon it. This is implied by the following verse [<i>ibid.</i>:39]: "Of what should a living man be aggrieved? [A man of his sins.]"<br>[The prophet] continues explaining, since free choice is in our hands and our own decision [is what prompts us to] commit all these wrongs, it is proper for us to repent and abandon our wickedness, for this choice is presently in our hand. This is implied by the following verse [<i>ibid.</i>:40]: "Let us search and examine our ways and return [to God]."', mimetype='text/plain', start_char_idx=0, end_char_idx=1566, text_template='{metadata_str}\n\n{content}'), score=0.6068722455455093)]

---

### ⚙️ Customizing the Retriever further

```python
from llama_index.core import MetadataFilters, ExactMatchFilter

retriever = index.as_retriever(
    similarity_top_k=5,
    filters=MetadataFilters(filters=[
        ExactMatchFilter(key="hilchot", value="Repentance")
    ])
)
```

You control:

* how many results (`top_k`)
* which parts of Rambam are searched
* filtering by metadata (e.g. Sefer HaMadda only)

👉 This controls **what information enters the system**

---

## 🎯 Key Insight

> The retriever does **not generate the answer**
> but it **determines what goes into the prompt**

So:

> **Better retrieval → better sources → better answer**

# Custom Grounded Answer Function (Instead of using using .query)

Now we manually build the RAG pipeline:

1. Retrieve relevant Rambam sources
2. Insert sources into a prompt
3. Ask the LLM to answer using only those sources
4. Return both the answer and source table

In [63]:
# Step 8 — Grounded answer function
from openai import OpenAI
from llama_index.core.schema import MetadataMode

client = OpenAI()


def retrieve_sources(index, query, k=5):
    retriever = index.as_retriever(similarity_top_k=k)
    nodes = retriever.retrieve(query)

    rows = []

    for node in nodes:
        md = node.metadata or {}

        rows.append({
            "ref": md.get("ref"),
            "hilchot": md.get("hilchot"),
            "chapter": md.get("chapter"),
            "halacha": md.get("halacha"),
            "score": getattr(node, "score", None),
            "text": node.get_content(metadata_mode=MetadataMode.NONE),
        })

    return pd.DataFrame(rows), nodes


def ask_rambam_with_sources(index, question, k=5):
    results_df, nodes = retrieve_sources(index, question, k=k)

    if results_df.empty:
        return {
            "answer": "I could not retrieve any relevant Rambam source.",
            "sources": results_df,
        }

    sources = "\n\n".join(
        f"{row['ref']}\n{row['text']}"
        for _, row in results_df.iterrows()
    )

    prompt = f'''
You are a Rambam assistant.

Answer in clear English.
Use ONLY the sources below.
Cite the references clearly.
Do not invent sources.
If the sources only partially answer the question, say so.

Question:
{question}

Sources:
{sources}
'''

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0,
        messages=[
            {"role": "user", "content": prompt}
        ],
    )

    return {
        "answer": response.choices[0].message.content,
        "sources": results_df,
    }

In [64]:
test = ask_rambam_with_sources(
    index,
    "What does Rambam say about free will?",
    k=5
)

print(test["answer"])
test["sources"]

Rambam, in his Mishneh Torah, discusses the concept of free will extensively, emphasizing that it is a fundamental principle of the Torah and mitzvot. He asserts that free will is granted to all individuals, allowing them to choose their path, whether it be good or evil (Mishneh Torah, Repentance 5:1). This ability to choose is what makes humans unique, as they can act according to their own initiative and desires without being compelled by any external force.

Rambam argues against the notion that God decrees whether a person will be righteous or wicked at the time of their creation. Instead, each person has the potential to be as righteous as Moses or as wicked as Jeroboam, and it is their own choice and initiative that determine their path (Mishneh Torah, Repentance 5:2). He emphasizes that no one compels or leads a person towards a particular path; rather, it is the individual's decision.

Furthermore, Rambam explains that if God had predetermined a person's behavior, the commandments of the Torah would be meaningless, as there would be no justice in rewarding the righteous or punishing the wicked. Instead, God desires that humans have free choice and be responsible for their actions, which is why they are judged according to their deeds (Mishneh Torah, Repentance 5:4).

In summary, Rambam's view is that free will is an essential aspect of human existence, allowing individuals to choose their actions and be accountable for them. This principle underpins the entire structure of the Torah and its commandments, highlighting the importance of personal responsibility and moral choice.

,ref,hilchot,chapter,halacha,score,text
0,"Mishneh Torah, Repentance 5:1",None,5,None,0.663053,Free will is granted to all men. If one desire...
1,"Mishneh Torah, Repentance 5:4",None,5,None,0.619322,Were God to decree that an individual would be...
2,"Mishneh Torah, Repentance 5:3",None,5,None,0.611243,This principle is a fundamental concept and a ...
3,"Mishneh Torah, Human Dispositions 1:2",None,1,None,0.609083,"Nevertheless, these are merely tendencies, and..."
4,"Mishneh Torah, Repentance 5:2",None,5,None,0.606872,A person should not entertain the thesis held ...

# Gradio
https://www.gradio.app


## Chat Interface Example

Your function must accept:

* `message` → the latest user input
* `history` → previous messages (conversation state)

```python
def chat_fn(message, history):
    ...
```

## Gradio Chat UI

Now we wrap the Q&A function in a simple chat interface.

In [ ]:
import gradio as gr
def chat_fn(message,history):
    return ask_rambam_with_sources(
        index,
        message,
        k=5
    )["answer"]

chat_interface = gr.ChatInterface(
    fn=chat_fn)
chat_interface.launch(debug=True,share=True)

/usr/local/lib/python3.12/dist-packages/gradio/chat_interface.py:347: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://3c23045f43ac004d56.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

# Prettier, More Custom Gradio App Version

In [ ]:
import os
import pandas as pd
import gradio as gr

# =========================
# Theme / CSS
# =========================
theme = gr.themes.Soft().set(
    body_background_fill="#f8f5ef",
    block_background_fill="#ffffff",
    block_border_width="1px",
    block_border_color="#e5dccb",
    button_primary_background_fill="#7a5c2e",
    button_primary_background_fill_hover="#644a24",
    button_primary_text_color="#ffffff",
    input_background_fill="#fffdf8",
)

css = """
.gradio-container {
    max-width: 1100px !important;
    margin: 0 auto !important;
}

#app-title {
    text-align: center;
    margin-bottom: 0.25rem;
}

#app-subtitle {
    text-align: center;
    color: #6b6257;
    margin-bottom: 1.25rem;
}

.rambam-card {
    border: 1px solid #e5dccb;
    border-radius: 18px;
    padding: 18px;
    background: linear-gradient(180deg, #fffdf8 0%, #faf6ee 100%);
    box-shadow: 0 6px 18px rgba(60, 40, 10, 0.06);
}

footer {display: none !important;}

.gr-button-primary {
    border-radius: 12px !important;
    font-weight: 600 !important;
}

textarea, .gr-text-input, .gr-textbox {
    border-radius: 12px !important;
}

.gr-chatbot {
    border-radius: 16px !important;
    border: 1px solid #e5dccb !important;
}

.source-box {
    font-size: 0.95rem;
    line-height: 1.5;
    color: #3d372f;
}
"""

# =========================
# Helpers
# =========================
def build_sources_markdown(results_df):
    if results_df is None or results_df.empty:
        return ""

    parts = []
    for row in results_df.itertuples(index=False):
        ref = getattr(row, "ref", "Unknown ref")
        text = getattr(row, "text", "")
        parts.append(f"**{ref}**\n{text}")

    return "\n\n---\n### Sources\n" + "\n\n".join(parts)


def retrieve_sources_safe(question, k=5):
    results_df, nodes = retrieve_sources(index,question, k=k)

    if results_df is None:
        results_df = pd.DataFrame(columns=["ref", "text"])

    if "ref" not in results_df.columns:
        results_df["ref"] = ""
    if "text" not in results_df.columns:
        results_df["text"] = ""

    return results_df, nodes


# =========================
# Streaming retrieval + LLM
# =========================
def ask_rambam_with_sources_stream(question, k=5):
    question = str(question).strip()

    results_df, _ = retrieve_sources_safe(question, k=k)

    if results_df.empty:
        context_text = "No Rambam sources were retrieved."
    else:
        context_text = "\n\n".join(
            f"REF: {row.ref}\nTEXT: {row.text}"
            for row in results_df.itertuples(index=False)
        )

    system_prompt = """
You are a helpful assistant answering questions about the Rambam.

Rules:
1. Answer ONLY from the provided Rambam sources.
2. If the sources do not clearly answer the question, say so clearly.
3. Be concise, clear, and faithful to the source text.
4. Do not invent facts, citations, or quotations.
5. Write in English unless the user asks otherwise.
""".strip()

    user_prompt = f"""
Question:
{question}

Retrieved Rambam sources:
{context_text}

Please answer based only on these sources.
""".strip()

    accumulated = ""

    with client.responses.stream(
        model="gpt-4.1",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    ) as stream:
        for event in stream:
            if event.type == "response.output_text.delta":
                delta = event.delta
                accumulated += delta
                yield accumulated

        final_response = stream.get_final_response()

    final_text = getattr(final_response, "output_text", None) or accumulated
    final_text += build_sources_markdown(results_df)
    yield final_text


# =========================
# ChatInterface handler
# IMPORTANT: this must YIELD for streaming
# =========================
def respond(message, history):
    if not str(message).strip():
        yield "Please enter a question."
        return

    try:
        for partial in ask_rambam_with_sources_stream(message, k=5):
            yield partial
    except Exception as e:
        yield f"Error: {e}"


# =========================
# UI
# =========================
with gr.Blocks(theme=theme, css=css) as demo:
    gr.Markdown("# Ask the Rambam", elem_id="app-title")
    gr.Markdown(
        "A source-grounded Rambam search app using Sefaria + semantic search.",
        elem_id="app-subtitle",
    )

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                height=600,
                show_label=False,
                avatar_images=(None, None),
            )

            gr.ChatInterface(
                fn=respond,          # streaming stays because respond() yields
                chatbot=chatbot,     # custom styled chatbot
            )

        with gr.Column(scale=1):
            gr.Markdown(
                """
<div class="rambam-card source-box">

### Tips
- Ask in plain English
- Try:
  - free will
  - repentance
  - Chol HaMoed work
  - returning lost objects

### Notes
Answers are grounded in Rambam sources.

</div>
                """
            )

demo.launch(
    prevent_thread_lock=True,
    debug=True,
    share=True
)s

/tmp/ipykernel_27251/4038549281.py:175: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(theme=theme, css=css) as demo:
/tmp/ipykernel_27251/4038549281.py:175: DeprecationWarning: The 'css' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'css' to Blocks.launch() instead.
  with gr.Blocks(theme=theme, css=css) as demo:
/tmp/ipykernel_27251/4038549281.py:184: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  chatbot = gr.Chatbot(
/tmp/ipykernel_27251/4038549281.py:184: DeprecationWarning: The default value of 'allow_tags' in gr.Chatbot will be changed from False to True in Gradio 6.0. You will need to explicitly set allow_tags=False if you want to disable tags in your chatbot.
  chatbot = gr.Chatbot(
/usr/local/lib/python3.12/dist-packages/gradio/chat_interface.py:330: UserWarning: The gr.ChatInterface was not provided with a type, so the type of the gr.Chatbot, 'tuples', will be used.
  warnings.warn(

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://e199f1108203fa0ce3.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)